; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.35/platform-espressif32.zip
board = esp32-c6-devkitm-1
upload_speed = 921600
board_build.mcu = esp32c6
framework = espidf, arduino
board_upload.flash_size = 4MB
board_build.partitions = partition.csv
platform_packages = 
		framework-espidf @ https://github.com/pioarduino/esp-idf/releases/download/v5.5.2/esp-idf-v5.5.2.tar.xz
		framework-arduino @ https://github.com/espressif/arduino-esp32/releases/download/3.3.5/esp32-3.3.5.zip
monitor_speed = 115200
lib_ldf_mode = chain
build_type = release
build_flags =
  -Wall
  -Wextra
  -Os
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_RUNNING_CORE=1
  -Wall
  -Wextra
  -Wunused
  -Wunused-parameter
  -Wunused-variable
  -Wunused-function
  -Wunused-but-set-variable
  -Wno-unused-parameter
lib_deps = 
	https://github.com/blemasle/arduino-as1115#583497e1ae78157a190364ddeabb53a7625a3b4a
	https://github.com/PaulStoffregen/Time#a18e50dcea4ee17285d732d39e7bc559482d1d3d
	https://github.com/arduino-libraries/NTPClient#e0e3b6571a7181600b7fdca8dc048931306ef186
	https://github.com/JChristensen/Timezone#633b0dca31cc44986880dda0005c24ec7ff4b83f
	https://github.com/cattanimarco/Grafici-GFX#575ef29b8b439096e717c9acc14eb4d02c9686b5
	https://github.com/janelia-arduino/AT42QT#d76fb0a92740f63aa64aa538837e6c18230e2486
	https://github.com/adafruit/Adafruit_SHT4X#76a06edfa280a699da1c2f311bdeccb0bd5cee92
	https://github.com/adafruit/Adafruit_BMP280_Library#4af9a4e49a7e2134def094aa0b7dc5a94387155c
	https://github.com/bblanchon/ArduinoJson#77771d3c07668e01d8f52acb03910c1110bb373f
	# mine
	https://github.com/themkoi/SparkFun_Ambient_Light_Sensor_Arduino_Library
	https://github.com/themkoi/Adafruit_SSD1327
	https://github.com/themkoi/Adafruit-GFX-Library
board_build.embed_txtfiles =     
    resources/certs/https_server.crt
    resources/certs/rmaker_mqtt_server.crt
    resources/certs/rmaker_claim_service_server.crt
    resources/certs/rmaker_ota_server.crt
custom_component_remove = 
	espressif/esp_hosted
	espressif/esp_wifi_remote
	espressif/esp-dsp
	espressif/network_provisioning
	espressif/esp-zboss-lib
	espressif/esp-zigbee-lib
	espressif/esp_rainmaker
	espressif/rmaker_common
	espressif/esp_insights
	espressif/esp_diag_data_store
	espressif/esp_diagnostics
	espressif/cbor
	espressif/qrcode
	espressif/esp-sr
	espressif/libsodium
	espressif/esp-modbus
	chmorgan/esp-libhelix-mp3
	espressif/esp32-camera
	# Added by me
	espressif/esp_modem